name: remedi_auth
description: Remedi Plugin Auth
version: 0.3.1
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter'

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #svg loader
  flutter_svg: ^1.1.4

  # kakao login
  kakao_flutter_sdk: ^1.2.1

  # sign in with apple
  sign_in_with_apple: ^4.1.0

  # phone verification
  firebase_auth: ^3.7.0

  # phone number input.
  expandable: ^5.0.1
  libphonenumber_plugin: ^0.2.3
  equatable: ^2.0.5
  collection: ^1.16.0

  #basic architecture of app
  stacked_mvvm: ^0.1.1

  remedi_widgets: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
